accounts/urls.py
from django.urls import path


from . import views

app_name = 'accounts'


urlpatterns = [
    path('register_photographer/', views.register_photographer, name='register_photographer'),
    path('register_client/', views.register_client, name='register_client'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password/', views.reset_password, name='reset_password'),
    
    
    # activation of accounts
    path('activate/<uidb64>/<token>/<account_type>/', views.activate, name='activate'),
    # reset password for a user
    path('reset_password_validate/<uidb64>/<token>/<account_type>/', views.reset_password_validate, name='reset_password_validate'),
]

folders/urls.py
from django.urls import path

from . import views

app_name = 'folders'


urlpatterns = [
    path('create_folder/', views.create_folder, name='create_folder'),
    
    # this is the upload thing-y happens
    path('upload_images/', views.upload_images, name='upload_images'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('upload_zip/', views.upload_zip, name='upload_zip'),
]

photo_template/urls.py
from django.urls import path

from . import views

app_name  = 'photo_template'


urlpatterns = [
    path('', views.index, name='index'),
    path('selection/', views.selection, name='selection'),
    path('photographer_dashboard/', views.p_dashboard, name='p_dashboard'),
    path('client_dashboard/', views.c_dashboard, name='c_dashboard'),
    path('search_token/', views.search_token, name='search_token'),
    path('search/', views.searched_folder, name='searched_folder')
]

snap_save/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo_template.urls')),
    path('accounts/', include('accounts.urls')),
    path('folders/', include('folders.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

photo_template/models.py
from django.db import models

# Create your models here.

photo_template/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .decorators import photographer_required, client_required
from django.contrib import messages

from folders.models import Folder
# Create your views here.


def index(request):
    return render(request, 'photo_template/index.html')


def selection(request):
    return render(request, 'photo_template/selection.html')


@login_required
@photographer_required
def p_dashboard(request):
    return render(request, 'photo_template/p_dashboard.html')


@login_required
@client_required
def c_dashboard(request):
    return render(request, 'photo_template/c_dashboard.html')

def search_token(request):
    return render(request, 'photo_template/search_token.html')

def searched_folder(request):
    if request.method == 'POST':
    # we now check if the request if it is a post request.
        token = request.POST.get('token')
        # getting the value that is in the name attribute
        try:
            folder = Folder.objects.get(token__exact=token)
            # the moment the user inserts the token, we update the trial field in the database
            folder.increment_token_usage
            
            # check if the token is expired after incrementing
            if folder.is_token_expired:
                messages.error(request, 'The token has expired.')
                return redirect('photo_template:c_dashboard')
            else:
                # render the search results
                context = {
                    'folder': folder,
                }
            return render(request, 'photo_template/searched_folder.html', context)
        except Folder.DoesNotExist:
            messages.error(request, 'Invalid token. Please try again.')
            return redirect('photo_template:c_dashboard')
    else:
        return render(request, 'photo_template/searched_folder.html')

photo_template/templates/photo_template/includes/alerts.html
{% if messages %}
{% for message in messages %}
    <div id="message" class="container my-3 text-center">
        <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
            <!-- <button type="button" class="close" data-dismiss="alert"></button> -->
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
            {{ message }}
        </div>
    </div>
    <!-- <span aria-hidden="true">&times;</span> -->
        {% endfor %}
{% endif %}

photo_template/templates/photo_template/includes/footer.html
<style>
  footer {
      margin-top: auto;
      background-color: rgba(52, 58, 64, 0.9);
      color: #fff;
      padding: 1rem 0;
      text-align: center;
      width: 100%;
    }
</style>

<footer class="bg-dark text-white">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <p>&copy; 2023 SnapShare. All rights reserved.</p>
        </div>
    </div>
  </footer>

photo_template/templates/photo_template/includes/navbar.html
{% load static %}

<style>
  .nav-link.border {
  border: 1px solid white;
  border-radius: 5px;
  padding: 5px 10px;
  margin-left: 10px;
  /* color: rgba(197, 197, 197, 0.897); */
}

</style>



{% load static %}

<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="#">
        <!-- Add your logo here -->
        <img src="" alt="SnapShare Logo" style="border-radius: 50%;" height="40">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          {% if user.is_authenticated %}
          <li class="nav-item d-none d-lg-block">
            <small class="nav-link text-white">Welcome, {{ user.first_name }}!</small>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'photo_template:index' %}">Home</a>
          </li>
          {% if user.is_photographer %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'photo_template:p_dashboard' %}">Dashboard</a>
          </li>
          {% elif user.is_client %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'photo_template:c_dashboard' %}">Dashboard</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item d-none d-lg-block">
            <small class="nav-link text-white">Welcome, User!</small>
          </li>
          <li class="nav-item nav-item d-none d-lg-block">
            <a class="nav-link text-white" href="{% url 'accounts:login' %}">Sign in</a>
          </li>
          <li class="nav-item nav-item d-none d-lg-block">
            <a class="nav-link border text-white" href="{% url 'photo_template:selection' %}">Register</a>
          </li>
          <li class="nav-item mt-3 nav-item d-lg-none d-sm-block">
            <a class="nav-link  text-white" href="{% url 'accounts:login' %}">Sign in</a>
          </li>
          <li class="nav-item nav-item d-lg-none d-sm-block">
            <a class="nav-link text-white" href="{% url 'photo_template:selection' %}">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</header>