folders/urls.py
from django.urls import path

from . import views

app_name = 'folders'


urlpatterns = [
    path('create_folder/', views.create_folder, name='create_folder'),
    
    # this is the upload thing-y happens
    path('upload_images/', views.upload_images, name='upload_images'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('upload_zip/', views.upload_zip, name='upload_zip'),
]

snap_save/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo_template.urls')),
    path('accounts/', include('accounts.urls')),
    path('folders/', include('folders.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

folders/models.py
from django.db import models
from accounts.models import Account

from django.utils import timezone
from datetime import timedelta
import uuid
# Create your models here.


class Folder(models.Model):
    # The name of the folder
    name = models.CharField(max_length=255)
    
    price = models.DecimalField(max_digits=10, decimal_places=2)

    # A description for the folder, optional
    description = models.TextField(blank=True)

    # The owner of the folder, linking to the User model
    owner = models.ForeignKey(Account, on_delete=models.CASCADE)

    # A unique token generated for the folder, used for various purposes
    token = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    # Counter for how many times the token has been used
    token_usage_count = models.PositiveIntegerField(default=0)

    # Timestamp for when the folder was created
    created_at = models.DateTimeField(auto_now_add=True)
    
    # adding expiry date for the token, set to 2days after creation
    expires_at = models.DateTimeField(default=timezone.now() + timedelta(days=2))

    # Property to check if the token is expired
    @property
    def is_token_expired(self):
        """
        Checks if the token has expired.
        The token is considered expired if it has been used more than 5 times
        or if the current time is past the expiry date.
        """
        return self.token_usage_count >= 8 or timezone.now() > self.expires_at

    # Method to increment the token usage count
    @property
    def increment_token_usage(self):
        """
        Increments the token usage count by 1 if the token is not expired.
        Saves the model instance after incrementing the count.
        """
        if not self.is_token_expired:
            self.token_usage_count += 1
            self.save()

    def __str__(self):
        return self.name
    
    
class UploadFile(models.Model):
    owner = models.ForeignKey(Account, on_delete=models.CASCADE)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images_uploaded')
    date_added = models.DateTimeField(auto_now_add=True)
    
    # def __str__(self):
    #     return str(self.image)
    
class UploadZip(models.Model):
    owner = models.ForeignKey(Account, on_delete=models.CASCADE)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)
    zip_file = models.FileField(verbose_name='zip_file', help_text='Please Upload Zip File')
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.zip_file)

folders/forms.py
from django import forms

from folders.models import Folder, UploadZip


class FolderCreationForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = [
            'name',
            'description',
            'price'
        ]
    name = forms.CharField(
        max_length=255,
        required=True,  # This makes the field required
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Folder Name',
            'style': 'color: rgba(107, 0, 194, 0.726);'
        })
    )
    
    price = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Price',
            'style': 'color: rgba(107, 0, 194, 0.726);'
        })
    )
    
    description = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'rows': 4,
            'placeholder': 'Folder Description(optional)'
        }),
        required=False  # This makes the field optional
    )
    
    

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput(attrs={
            'class': 'form-control',  # Add your custom class here
            'style': 'margin-bottom: 1rem;',  # Add any inline styles here
        }))
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = [single_file_clean(data, initial)]
        return result

class UploadFileForm(forms.Form):
    folder = forms.ModelChoiceField(
        queryset=Folder.objects.all(),
        required=True,
        widget=forms.Select(attrs={
            'class': 'form-control form-select fw-bold',  # Add your custom class here
            'style': 'margin-bottom: 1rem;',  # Add any inline styles here
        })
    )
    images = MultipleFileField(
        required=True,
        widget=MultipleFileInput(attrs={
            'class': 'form-control',  # Add your custom class here
            'style': 'margin-bottom: 1rem;',  # Add any inline styles here
        })
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['folder'].choices = [('', 'Select a folder')] + list(self.fields['folder'].choices)
        
        
class UploadZipForm(forms.ModelForm):
    class Meta:
        model = UploadZip
        fields = ['folder', 'zip_file']
        widgets = {
            'folder': forms.Select(attrs={
                'class': 'form-control fw-bold', 
                'style': 'margin-bottom: 1rem;',
                'placeholder': 'Select a folder'
            }),
            'zip_file': forms.ClearableFileInput(attrs={
                'class': 'form-control'
            }),
        }
        labels = {
            'zip_file': 'Choose Zip File',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['folder'].choices = [('', 'Select a folder')] + list(self.fields['folder'].choices)

folders/views.py
from django.shortcuts import render, redirect

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Folder, UploadFile
from .forms import FolderCreationForm, UploadFileForm, UploadZipForm
from photo_template.decorators import photographer_required
from .reused_func import send_token


from django.http import HttpResponse
from django.http import JsonResponse

# for the zip file, It seems I really need to import lots of dependecies
import zipfile #importing the zipfile module to handle ZIP file operations
import os #importing os module to handle file and directory paths
from django.conf import settings #importing this to use the django settings

# Create your views here.


@login_required
@photographer_required
def create_folder(request):
    # to get rid of the not null constraint, we need to set the owner field to the logged in user
    user = request.user
    token = None
    # for one to create a folder, we need to check whether if the request is a get or post request
    if request.method != 'POST':
        # send out the form again as it is not a POST request
        form = FolderCreationForm()
    else:
        # accept the form with the data that it has been submitted with
        form = FolderCreationForm(request.POST)
        # print(form)
        # now we need to check to see if the form is valid
        if form.is_valid():
            # use the try-except block
            try:
                # now, we get the the two fields and save them in variables
                name = form.cleaned_data['name']
                price = form.cleaned_data['price']
                # this here is written like this because, in case a user intentionally left the field empty, a default string is provided which won't cause error
                description = form.cleaned_data.get('description', '')
                # now after this, we call the folder class to make an instance of it
                folder = Folder.objects.create(name=name, price=price, owner=user, description=description)
                folder.save()
                token = folder.token  # Get the generated token for the folder
                
                # send a token to the user email
                send_token(request, user.email, token)
                # send a message to the user notify them that a token has been generated for them for that specific folder
                messages.success(request, f'A token for {folder.name} has been generated for you. Please check your email')
                # Pass the token to the context
                context = {
                    'form': FolderCreationForm(),
                    'token': token
                }
                return render(request, 'folders/create_folder.html', context)
            except Exception as e:
                print(e)
    context = {
        'form':form,
        'token':token
    }
    return render(request, 'folders/create_folder.html', context)


@login_required
@photographer_required
def upload_images(request):
    return render(request, 'folders/upload_images.html')


@login_required
@photographer_required
def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            folder = form.cleaned_data['folder']
            files = form.cleaned_data['images']

            for file in files:
                UploadFile.objects.create(owner=request.user, folder=folder, image=file)

            return JsonResponse({'success': True})  # Return JSON response
        else:
            return JsonResponse({'success': False, 'errors': form.errors}, status=400)
    else:
        form = UploadFileForm()

    context = {
        'form': form
    }
    return render(request, 'folders/upload_file.html', context)


@login_required
@photographer_required
def upload_zip(request):
    if request.method != 'POST':
        # return the form back to the user
        form = UploadZipForm()
    
    else:
        form = UploadZipForm(request.POST, request.FILES) #Initializing the form with the POST data and uploaded
        # checking if the form is valid
        if form.is_valid():
            try:
                zip_instance = form.save(commit=False) #saving the form but not committing to the database yet
                zip_instance.owner = request.user # Setting the owner of the ZIP file to the current user
                zip_instance.save() # Saving the ZIP file instance to the database
                
                return redirect('folders:upload_zip')
            except:
                pass
    context = {
        'form':form
    }        
    return render(request, 'folders/upload_zip.html', context)

folders/templates/folders/create_folder.html
{% extends 'photo_template/base.html' %}



{% block title %}
Create Folder - SnapShare
{% endblock title %}


{% block css %}
    body {
      background-color: #f8f9fa;
      cursor: url('https://i.imgur.com/DmBTFWT.png'), auto;
      font-family: 'Poppins', sans-serif;
      color: #333;
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }

    .create-folder {
      flex-grow: 1;
      display: flex;
      align-items: center;
      justify-content: center;
      text-align: center;
    }

    .create-folder h1 {
      font-size: clamp(2rem, 5vw, 4rem);
      font-weight: bold;
      margin-bottom: 2rem;
      animation: fadeInUp 1s;
    }

    .create-folder form {
      max-width: 400px;
      width: 100%;
    }

    .create-folder form input,
    .create-folder form textarea {
      width: 100%;
      margin-bottom: 1rem;
      padding: 1rem;
      font-size: 1rem;
      border-radius: 5px;
      border: 1px solid #ced4da;
    }

    .create-folder .btn {
      width: 100%;
      padding: 1rem;
      font-size: 1rem;
      font-weight: bold;
      border-radius: 5px;
      transition: transform 0.3s ease-in-out, background-color 0.3s ease-in-out;
    }

    .create-folder .btn:hover {
      transform: translateY(-5px);
    }

    .folder-token-section {
      width: 100%;
      max-width: 500px;
      margin: auto;
    }

    .input-group .btn {
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .input-group .btn i {
      pointer-events: none;
    }

    footer {
      margin-top: auto;
    }

{% endblock css %}



{% block content %}

  <main class="create-folder my-5">
    <div class="container">
      {% include 'photo_template/includes/alerts.html' %}
      <h1 class="animate__animated animate__fadeInUp">Create Folder</h1>
      <form action="{% url 'folders:create_folder' %}" method="POST" class="animate__animated animate__fadeInUp">
        {% csrf_token %}
        <div class="form-group">
          {{ form.name }}
        </div>
        <div class="form-group">
          {{ form.price }}
        </div>
        <div class="form-group">
          {{ form.description }}
        </div>
        <button type="submit" class="btn btn-primary">Create Folder</button>
      </form>
    </div>
  </main>
  {% if token %}
  <div class="container mt-2 mb-4 folder-token-section" style="max-width: 500px;">
    <label for="folderToken" class="form-label fw-bold">Folder Token</label>
    <div class="input-group">
      <input type="text" id="folderToken" class="form-control" value="{{ token }}" readonly>
      <button class="btn btn-secondary" type="button" onclick="copyToken()" aria-label="Copy token">
        <i class="fas fa-clipboard"></i>
      </button>
    </div>
  </div>
{% endif %}

  <script>
    function copyToken() {
      var copyText = document.getElementById("folderToken");
      copyText.select();
      copyText.setSelectionRange(0, 99999); /* For mobile devices */
      document.execCommand("copy");
      alert("Token copied: " + copyText.value);
    }
  </script>

{% endblock content %}

folders/templates/folders/send_folder_token.html
<html>
<head>
    <title>Folder Token</title>
</head>
<body>
    <p>Dear {{ user.first_name }},</p>
    <p>Thank you for creating a folder. Here is your token:</p>
    <p><strong>{{ token }}</strong></p>
    <p>You can use this token for accessing the folder. The token is valid for 5 uses.</p>
    <p>Best regards,<br>Snap Save</p>
</body>
</html>

folders/templates/folders/upload_file.html
{% extends 'photo_template/base.html' %}

{% load crispy_forms_tags %}

{% block title %}
Upload Files - SnapShare
{% endblock title %}

{% block css %}
    body {
      background-color: #f8f9fa;
      font-family: 'Poppins', sans-serif;
      color: #333;
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }

    .upload-files {
      flex-grow: 1;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 2rem;
    }

    .upload-container {
      text-align: center;
      width: 100%;
    }

    .upload-title {
      font-size: 2.5rem;
      font-weight: bold;
      margin-bottom: 2rem;
      color: #333;
      animation: fadeInUp 1s;
    }

    .upload-form {
      max-width: 500px;
      width: 100%;
      padding: 2rem;
      border-radius: 8px;
      background-color: #fff;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
      animation: fadeInUp 1s;
    }

    .upload-form .form-group {
      margin-bottom: 1.5rem;
    }

    .upload-form .form-control,
    .upload-form .form-select {
      width: 100%;
      padding: 0.75rem;
      font-size: 1rem;
      border-radius: 5px;
      border: 1px solid #ced4da;
      transition: border-color 0.3s ease-in-out, box-shadow 0.3s ease-in-out;
    }

    .upload-form .form-control:focus,
    .upload-form .form-select:focus {
      border-color: #80bdff;
      box-shadow: 0 0 8px rgba(0, 123, 255, 0.25);
    }

    .upload-form input[type="file"] {
      display: none;
    }

    .upload-form label {
      display: block;
      width: 100%;
      padding: 0.75rem;
      margin-bottom: 1rem;
      font-size: 1rem;
      font-weight: bold;
      text-align: center;
      color: #fff;
      background-color: #007bff;
      border-radius: 5px;
      cursor: pointer;
      transition: background-color 0.3s ease-in-out;
    }

    .upload-form label:hover {
      background-color: #0056b3;
    }

    .upload-form .upload-btn {
      display: block;
      width: 100%;
      padding: 0.75rem;
      font-size: 1rem;
      font-weight: bold;
      border: none;
      color: #fff;
      background-color: #28a745;
      border-radius: 5px;
      cursor: pointer;
      transition: background-color 0.3s ease-in-out;
    }

    .upload-form .upload-btn:hover {
      background-color: #218838;
    }

    .progress {
      width: 100%;
      height: 1.5rem;
      margin-top: 1rem;
      background-color: #e9ecef;
      border-radius: 5px;
      overflow: hidden;
      display: none;
    }

    .progress-bar {
      height: 100%;
      background-color: #007bff;
      border-radius: 5px;
      transition: width 0.3s ease-in-out;
    }

    .success-message {
      display: none;
      margin-top: 1rem;
      color: #28a745;
      font-weight: bold;
    }

    .error-message {
      display: none;
      margin-top: 1rem;
      color: #dc3545;
      font-weight: bold;
    }

    @keyframes fadeInUp {
      from {
        opacity: 0;
        transform: translateY(20px);
      }
      to {
        opacity: 1;
        transform: translateY(0);
      }
    }
{% endblock css %}

{% block content %}
  <main class="upload-files">
    <div class="upload-container">
      <h1 class="upload-title">Upload Files</h1>
      <form id="upload-form" method="post" enctype="multipart/form-data" action="{% url 'folders:upload_file' %}">
        {% csrf_token %}
        <div class="form-group">
          {{ form.folder }}
        </div>
        <div class="form-group">
          {{ form.images }}
        </div>
        <button type="button" class="upload-btn btn btn-lg btn-primary" id="upload-btn" disabled>Upload</button>
        <div class="progress mt-3">
          <div class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <div class="success-message" id="success-message">Upload Complete!</div>
        <div class="error-message" id="error-message">Please select a folder and at least one image.</div>
      </form>
    </div>
  </main>

  <script>
    const folderSelect = document.getElementById('id_folder');
    const fileUploadInput = document.getElementById('id_images');
    const uploadBtn = document.getElementById('upload-btn');
    const progressBar = document.querySelector('.progress-bar');
    const progressContainer = document.querySelector('.progress');
    const successMessage = document.getElementById('success-message');
    const errorMessage = document.getElementById('error-message');

    const validateForm = () => {
      if (folderSelect.value !== '' && fileUploadInput.files.length > 0) {
        uploadBtn.disabled = false;
        errorMessage.style.display = 'none';
      } else {
        uploadBtn.disabled = true;
      }
    };

    folderSelect.addEventListener('change', validateForm);
    fileUploadInput.addEventListener('change', validateForm);

    uploadBtn.addEventListener('click', () => {
      if (folderSelect.value === '' || fileUploadInput.files.length === 0) {
        errorMessage.style.display = 'block';
        return;
      }

      const files = fileUploadInput.files;
      if (files.length > 0) {
        const formData = new FormData(document.getElementById('upload-form'));

        progressContainer.style.display = 'block';
        successMessage.style.display = 'none';
        errorMessage.style.display = 'none';

        fetch('{% url "folders:upload_file" %}', {
          method: 'POST',
          body: formData,
          headers: {
            'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
          },
        }).then(response => response.json()).then(data => {
          if (data.success) {
            successMessage.style.display = 'block';
            progressContainer.style.display = 'none';
            window.location.href = '{% url "folders:upload_file" %}';  // Redirect after successful upload
          } else {
            console.error('Upload failed:', data.errors);
          }
        }).catch(error => console.error('Upload failed:', error));

        // Simulate upload progress for demonstration
        let uploadedSize = 0;
        const totalSize = Array.from(files).reduce((acc, file) => acc + file.size, 0);
        const interval = setInterval(() => {
          if (uploadedSize < totalSize) {
            uploadedSize += totalSize * 0.1; // Simulate 10% upload at a time
            const progress = Math.min((uploadedSize / totalSize) * 100, 100);
            progressBar.style.width = `${progress}%`;
            progressBar.setAttribute('aria-valuenow', progress);
          } else {
            clearInterval(interval);
            progressBar.style.width = '100%';
            progressBar.setAttribute('aria-valuenow', 100);
            successMessage.style.display = 'block';
            progressContainer.style.display = 'none';
          }
        }, 500); // Update progress every 500ms
      }
    });
  </script>
{% endblock content %}

folders/templates/folders/upload_images.html
{% extends 'photo_template/base.html' %}



{% block title %}
Upload Pictures - SnapShare
{% endblock title %}

{% block css %}
    body {
      background-color: #f8f9fa;
      cursor: url('https://i.imgur.com/DmBTFWT.png'), auto;
      font-family: 'Poppins', sans-serif;
      color: #333;
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }

    .upload-pictures {
      flex-grow: 1;
      display: flex;
      align-items: center;
      justify-content: center;
      text-align: center;
      padding: 3rem 0;
    }

    .upload-pictures h1 {
      font-size: clamp(2rem, 5vw, 4rem);
      font-weight: bold;
      margin-bottom: 2rem;
      animation: fadeInUp 1s;
    }

    .upload-pictures .btn-group {
      width: 100%;
      display: flex;
      justify-content: center;
      gap: 1rem;
      flex-wrap: wrap;
      margin-bottom: 2rem;
    }

    .upload-pictures .btn {
      padding: 1.5rem 3rem;
      font-size: 1.5rem;
      font-weight: bold;
      border-radius: 5px;
      transition: transform 0.3s ease-in-out, background-color 0.3s ease-in-out;
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 0.5rem;
    }

    .upload-pictures .btn:hover {
      transform: translateY(-5px);
    }

    .btn-primary {
      background-color: #007bff;
      border: none;
    }

    .btn-primary:hover {
      background-color: #0056b3;
    }

    .btn-secondary {
      background-color: #6c757d;
      border: none;
    }

    .btn-secondary:hover {
      background-color: #545b62;
    }

    footer {
      margin-top: auto;
      background-color: rgba(52, 58, 64, 0.9);
      color: #fff;
      padding: 1rem 0;
      text-align: center;
      width: 100%;
    }

    @media (max-width: 767px) {
      .upload-pictures .btn-group {
        flex-direction: column;
      }

      .upload-pictures .btn {
        margin-bottom: 1rem;
      }
    }

{% endblock css %}

{% block content %}
  <main class="upload-pictures">
    <div class="container">
      <h1 class="animate__animated animate__fadeInUp">Upload Pictures</h1>
      <div class="btn-group animate__animated animate__fadeInUp">
        <a href="{% url 'folders:upload_file' %}" class="btn btn-primary mx-4">
          <i class="fas fa-file-upload"></i> Upload Files
        </a>
        <a href="{% url 'folders:upload_zip' %}" class="btn btn-secondary">
          <i class="fas fa-file-archive"></i> Upload Zip
        </a>
      </div>
    </div>
  </main>
{% endblock content %}

folders/templates/folders/upload_zip.html
{% extends 'photo_template/base.html' %}

{% block title %}
Upload Zip - SnapShare
{% endblock title %}

{% block css %}
body {
  background-color: #f8f9fa;
  font-family: 'Poppins', sans-serif;
  color: #333;
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

.upload-files {
  flex-grow: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 2rem;
}

.upload-container {
  text-align: center;
  width: 100%;
}

.upload-title {
  font-size: 2.5rem;
  font-weight: bold;
  margin-bottom: 2rem;
  color: #333;
  animation: fadeInUp 1s;
}

.upload-form {
  max-width: 500px;
  width: 100%;
  padding: 2rem;
  border-radius: 8px;
  background-color: #fff;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
  animation: fadeInUp 1s;
}

.upload-form .form-group {
  margin-bottom: 1.5rem;
}

.upload-form .form-control,
.upload-form .form-select {
  width: 100%;
  padding: 0.75rem;
  font-size: 1rem;
  border-radius: 5px;
  border: 1px solid #ced4da;
  transition: border-color 0.3s ease-in-out, box-shadow 0.3s ease-in-out;
}

.upload-form .form-control:focus,
.upload-form .form-select:focus {
  border-color: #80bdff;
  box-shadow: 0 0 8px rgba(0, 123, 255, 0.25);
}

.upload-form .upload-btn {
  display: block;
  width: 100%;
  padding: 0.75rem;
  font-size: 1rem;
  font-weight: bold;
  border: none;
  color: #fff;
  background-color: #28a745;
  border-radius: 5px;
  cursor: pointer;
  transition: background-color 0.3s ease-in-out;
}

.upload-form .upload-btn:hover {
  background-color: #218838;
}

.upload-form .upload-btn:disabled {
  background-color: #6c757d;
  cursor: not-allowed;
}

.progress {
  width: 100%;
  height: 1.5rem;
  margin-top: 1rem;
  background-color: #e9ecef;
  border-radius: 5px;
  overflow: hidden;
  display: none;
}

.progress-bar {
  height: 100%;
  background-color: #007bff;
  border-radius: 5px;
  transition: width 0.3s ease-in-out;
}

.success-message {
  display: none;
  margin-top: 1rem;
  color: #28a745;
  font-weight: bold;
}

.error-message {
  display: none;
  margin-top: 1rem;
  color: #dc3545;
  font-weight: bold;
}

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
{% endblock css %}

{% block content %}
<main class="upload-files">
  <div class="upload-container">
    <h1 class="upload-title">Upload Zip</h1>
    <form id="upload-form" method="post" enctype="multipart/form-data" action="{% url 'folders:upload_zip' %}">
      {% csrf_token %}
      <div class="form-group">
        {{ form.folder }}
      </div>
      <div class="form-group">
        {{ form.zip_file }}
      </div>
      <button type="submit" class="upload-btn mt-3 btn btn-lg btn-primary" id="upload-btn" disabled>Upload</button>
      <div class="progress mt-3">
        <div class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <div class="success-message" id="success-message">Upload Complete!</div>
      <div class="error-message" id="error-message">Please select a folder and choose a ZIP file to upload.</div>
    </form>
  </div>
</main>

<script>
document.addEventListener('DOMContentLoaded', function () {
  const folderInput = document.getElementById('id_folder');
  const zipFileInput = document.getElementById('id_zip_file');
  const uploadBtn = document.getElementById('upload-btn');

  function validateForm() {
    if (folderInput.value && zipFileInput.files.length > 0) {
      uploadBtn.disabled = false;
    } else {
      uploadBtn.disabled = true;
    }
  }

  folderInput.addEventListener('change', validateForm);
  zipFileInput.addEventListener('change', validateForm);
});
</script>
{% endblock content %}