accounts/urls.py
from django.urls import path


from . import views

app_name = 'accounts'


urlpatterns = [
    path('register_photographer/', views.register_photographer, name='register_photographer'),
    path('register_client/', views.register_client, name='register_client'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password/', views.reset_password, name='reset_password'),
    
    
    # activation of accounts
    path('activate/<uidb64>/<token>/<account_type>/', views.activate, name='activate'),
    # reset password for a user
    path('reset_password_validate/<uidb64>/<token>/<account_type>/', views.reset_password_validate, name='reset_password_validate'),
]

folders/urls.py
from django.urls import path

from . import views

app_name = 'folders'


urlpatterns = [
    path('create_folder/', views.create_folder, name='create_folder'),
    
    # this is the upload thing-y happens
    path('upload_images/', views.upload_images, name='upload_images'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('upload_zip/', views.upload_zip, name='upload_zip'),
]

snap_save/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo_template.urls')),
    path('accounts/', include('accounts.urls')),
    path('folders/', include('folders.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/forms.py
from django import forms

from .models import Account


# this is the registrationForm for both the photographer and the client
class PhotoRegistrationForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Password',
                'class':'form-control',
                'required':'Please enter your password',
                # 'name':'password'
            }
        )
    )
    
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Confirm Password',
                'class':'form-control',
                'required':'Please enter your password',
                # 'name':'confirm_password'
            }
        )
    )
    
    class Meta:
        model = Account
        fields = [
            'first_name',
            'last_name',
            'email',
            'phone_number',
            'bank_number',
            'password',
            ]
        
    
    
    def __init__(self, *args, **kwargs):
        super(PhotoRegistrationForm, self).__init__(*args, **kwargs)
        
        # this here is the bootstrap classes given to each field
        self.fields['first_name'].widget.attrs['placeholder'] = 'First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Phone Number'
        self.fields['phone_number'].widget.attrs['type'] = 'tel'
        self.fields['bank_number'].widget.attrs['placeholder'] = 'Bank Account'
        self.fields['bank_number'].widget.attrs['type'] = 'number'
        # self.fields['bank_number'].widget.attrs['min'] = '0'
        # self.fields['bank_number'].widget.attrs['step'] = '1'
        
        
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            
    def clean(self):
        cleaned_data = super(PhotoRegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        
        
        if len(password) < 8:
            raise forms.ValidationError("Password must be at least 8 characters long.")
        
        
        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match. Please enter the same password in both fields.")
        

class ClientRegistrationForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Password',
                'class':'form-control',
                'required':'Please enter your password',
                # 'name':'password'
            }
        )
    )
    
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Confirm Password',
                'class':'form-control',
                'required':'Please enter your password',
                # 'name':'confirm_password'
            }
        )
    )
    
    class Meta:
        model = Account
        fields = [
            'first_name',
            'last_name',
            'email',
            'phone_number',
            'password',
        ]
        
        
    def __init__(self, *args, **kwargs):
        super(ClientRegistrationForm, self).__init__(*args, **kwargs)
        
        # this here is the bootstrap classes given to each field
        self.fields['first_name'].widget.attrs['placeholder'] = 'First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Phone Number'
        self.fields['phone_number'].widget.attrs['type'] = 'tel'
        
        
        
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            
    def clean(self):
        cleaned_data = super(ClientRegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        
        
        if len(password) < 8:
            raise forms.ValidationError("Password must be at least 8 characters long.")
        
        
        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match. Please enter the same password in both fields.")
        
        
        

accounts/views.py
from django.shortcuts import render, redirect


from .forms import PhotoRegistrationForm, ClientRegistrationForm
from .models import Account

# refactored functions
from .refactored_functions import send_activation_link, send_password_reset_link, decode_uid
import requests
from django.contrib.auth.decorators import login_required
# what i need for the email activation
from django.contrib.auth.tokens import default_token_generator
from django.contrib import messages, auth
# from django.http import HttpResponse
# Create your views here.



def register_photographer(request):
    if request.method != 'POST':
        # if the form is not post, then just submit an empty form, then render the form again due to error from the field or non-field error
        form = PhotoRegistrationForm()
    else:
        # submit the data that was submitted via post request
        form = PhotoRegistrationForm(request.POST)
        if form.is_valid():
            try:
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                email = form.cleaned_data['email']
                phone_number = form.cleaned_data['phone_number']
                bank_number = form.cleaned_data['bank_number']
                password = form.cleaned_data['password']
                
                username = email.split('@')[0]
                
                # Need to make the necessary fields, then assign them to the account model, which it will create a user for us
                user = Account.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email, password=password)
                
                # Save additional fields
                user.phone_number = phone_number
                user.bank_number = bank_number
                user.save()
                
                # Call the function to send activation link
                send_activation_link(request, user, email, 'photographer')
                return redirect('/accounts/login/?command=verification&email='+email)
            
            except Exception:
                messages.error(request, 'An error occurred during registration.')
                return redirect('accounts:register_photographer')
            
    context = {
        'form': form,
    }
    return render(request, 'accounts/p_registration.html', context)



def register_client(request):
    # check if the request is whether a post or get 
    if request.method != 'POST':
        # send out the form again to them to fill in
        form = ClientRegistrationForm()
    else:
        form = ClientRegistrationForm(request.POST)
        # now checks, if the form is valid, then a client account will be created and an activation link will be sent
        if form.is_valid():
            try:
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                email = form.cleaned_data['email']
                phone_number= form.cleaned_data['phone_number']
                password = form.cleaned_data['password']
                
                username = email.split('@')[0]
                
                # now after this, a user will be created
                user = Account.objects.create_user(first_name=first_name, last_name=last_name, email=email, username=username, password=password)
                # now after all this been created, then assigned the phone number to the phone number field in the database
                user.phone_number = phone_number
                user.save()
                
                # now we call the send_activation link to send email to our user
                send_activation_link(request, user, email, 'client')
                return redirect('/accounts/login/?command=verification&email='+email)
            except Exception:
                messages.error(request, 'An error occurred during registration.')
                return redirect('accounts:register_client')
            
    context = {
        'form': form,
    }
            
    return render(request, 'accounts/c_registration.html', context)




def activate(request, uidb64, token, account_type):
    """
    Activate the user account using the provided UID, token, and account type.

    Args:
        request (HttpRequest): The HTTP request object.
        uidb64 (str): The base64 encoded UID.
        token (str): The activation token.
        account_type (str): The type of account to activate ('photographer' or 'client').

    Returns:
        HttpResponseRedirect: Redirects to the appropriate page after activation.
    """
    # Decode the UID from base64
    uid = decode_uid(uidb64)

    # If UID decoding fails, show error message and redirect
    if not uid:
        messages.error(request, 'Invalid activation link: User does not exist.')
        return redirect('photo_template:selection')

    try:
        # Get the user with the decoded UID
        user = Account._default_manager.get(pk=uid)
    except Account.DoesNotExist:
        # If user does not exist, show error message and redirect
        messages.error(request, 'Invalid activation link: User does not exist.')
        return redirect('photo_template:selection')

    # If user account is already active, show warning message
    if user.is_active:
        messages.warning(request, 'Your account has already been activated.')
    # If activation token is valid, activate user account
    elif default_token_generator.check_token(user, token):
        user.is_active = True
        if account_type == 'photographer':
            user.is_photographer = True
        elif account_type == 'client':
            user.is_client = True
        user.save()
        messages.success(request, 'Congratulations! Your account has been activated.')
    else:
        # If activation token is invalid, show error message and redirect
        messages.error(request, 'Invalid activation link: The token is invalid')
        return redirect('photo_template:selection')

    # Redirect to the appropriate page after activation
    if user.is_photographer:
        return redirect('photo_template:p_dashboard')
    elif user.is_client:
        return redirect('photo_template:c_dashboard')



# THIS IS THE LOGIN VIEW
def login(request):
    # Check if the request method is POST (i.e., form submission)
    if request.method == 'POST':
        # Extract email and password from the submitted form
        email = request.POST.get('email')
        password = request.POST.get('password')
        
        try:
            # Authenticate the user with the provided email and password
            user = auth.authenticate(email=email, password=password)
            # If authentication is successful (i.e., user exists and provided correct credentials)
            if user is not None:
                # Log in the user
                auth.login(request, user)
                # Get the URL of the previous page (if available)
                url = request.META.get('HTTP_REFERER')
                try:
                    # If the previous page URL exists
                    if url:
                        # Parse the query parameters from the URL
                        query = requests.utils.urlparse(url).query
                        # Extract query parameters and store them in a dictionary
                        params = dict(x.split('=') for x in query.split('&'))
                        # If 'next' parameter is present in the query parameters
                        if 'next' in params:
                            # Redirect the user to the page specified in the 'next' parameter
                            next_page = params['next']
                            return redirect(next_page)
                # Handle exceptions related to URL parsing or redirection
                except Exception as e:
                    pass

                if user.is_photographer:
                    # Display a success message and redirect the user to the default page
                    messages.success(request, f'Welcome to your dashboard, {user.first_name}.')
                    return redirect('photo_template:p_dashboard')
                if user.is_client:
                    messages.success(request, f'Welcome to your dashboard, {user.first_name}.')
                    return redirect('photo_template:c_dashboard')
                
            else:
                # If authentication fails, display an error message and redirect back to the login page
                messages.error(request, 'Invalid login credentials!')
                return redirect('accounts:login')
        # Handle any exceptions that might occur during the login process
        except Exception as e:
            messages.error(request, 'An error occurred during login. Please try again later.')
            return redirect('accounts:login')
    
    # Render the login form template for GET requests
    return render(request, 'accounts/login.html')

@login_required()
def logout(request):
    auth.logout(request)
    messages.info(request, f'You have logged out. Visit us again.')
    return redirect('accounts:login')



# THIS IS THE FORGOT_PASSWORD VIEW
def forgot_password(request):
    # checks if the data is submitted via POST request
    if request.method == 'POST':
        email = request.POST.get('email')
        
        # when the email is gotten, we check our database and see whether that email exists or not
        if Account.objects.filter(email=email).exists():
            # if a user with that email exists, then get the email with the exact wording
            user = Account.objects.get(email__exact=email)
            
            # now it checks the flags whether that user is a photographer or a client
            
            if user.is_photographer:
                # now we send an email with the encrypted primary key of the user to their email

accounts/templates/accounts/account_verification_email.html
{% autoescape off %}
Hi {{ user.first_name }},

Please click on the below link to activate your account.
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token account_type=user_type %}

If you think it is not you that requested for this link, please ignore.

{% endautoescape %}

accounts/templates/accounts/c_registration.html
{% extends 'photo_template/base.html' %}

{% block title %}
  SnapShare - Register
{% endblock title %}


{% block css %}
    body {
      background-color: #f8f9fa;
      cursor: url('https://i.imgur.com/DmBTFWT.png'), auto;
      font-family: 'Poppins', sans-serif;
      color: #333;
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }

    .register {
      flex-grow: 1;
      display: flex;
      align-items: center;
      justify-content: center;
      text-align: center;
      background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://source.unsplash.com/random/1920x1080?photography');
      background-size: cover;
      background-position: center;
      color: #fff;
    }

    .register-form {
      max-width: 400px;
      background-color: rgba(255, 255, 255, 0.9);
      padding: 2rem;
      border-radius: 10px;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.3);
    }

    .register-form h2 {
      font-size: 2rem;
      font-weight: bold;
      margin-bottom: 1.5rem;
      text-align: center;
    }

    .register-form .form-group {
      margin-bottom: 1.5rem;
    }

    .register-form .form-control {
      border-radius: 0;
      background-color: transparent;
      border: none;
      border-bottom: 2px solid #ff4d4d;
      color: #333;
      font-size: 1rem;
      padding: 0.5rem 0;
    }

    .register-form .form-control:focus {
      background-color: transparent;
      border-color: #e63333;
      box-shadow: none;
    }

    .register-form .btn {
      background-color: #ff4d4d;
      color: #fff;
      font-weight: bold;
      border-radius: 0;
      transition: background-color 0.3s ease-in-out;
    }

    .register-form .btn:hover {
      background-color: #e63333;
    }

        /* Hide number input spinner and arrow buttons */
    input[type=number]::-webkit-inner-spin-button,
    input[type=number]::-webkit-outer-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    input[type=number] {
        -moz-appearance: textfield; /* Firefox */
    }

    .non_field_errors {
      color: red; /* Change the color to your desired color */
      /* Add any other styling properties as needed */
  } 

    @media (max-width: 767px) {
      .register {
        padding: 4rem 1rem;
      }
    }
{% endblock css %}

{% block content %}
  <main class="register">
    <div class="container mt-4 mb-4">
      <div class="register-form animate__animated animate__fadeInUp">
        <h2 class="text-dark">Register</h2>
        <form action="{% url 'accounts:register_client' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <!-- <input name="first_name" type="text" class="form-control" placeholder="First Name"> -->
            {{ form.first_name }}
          </div>
          <div class="form-group">
            <!-- <input type="text" name="last_name" class="form-control" placeholder="Last Name"> -->
            {{ form.last_name }}
          </div>
          <div class="form-group">
            <!-- <input type="email" name="email" class="form-control" placeholder="Email"> -->
            {{ form.email }}
          </div>
          <div class="form-group">
            <!-- <input type="email" name="email" class="form-control" placeholder="Email"> -->
            {{ form.phone_number }}
          </div>
          <div class="form-group">
            <!-- <input type="password" name="password" class="form-control" placeholder="Password"> -->
            {{ form.password }}
          </div>
          <div class="form-group">
            <!-- <input type="password"  class="form-control" placeholder="Confirm Password"> -->
            {{ form.confirm_password }}
          </div>
          <button type="submit" class="btn btn-block">Register</button>
          <p class="text-center text-dark mt-4">Have an account? <a href="{% url 'accounts:login' %}">Log In</a></p>
          <div class="form-group text-center non_field_errors">
            {{ form.email.errors }}
            {{ form.non_field_errors }}
          </div>
        </form>
      </div>
    </div>
  </main>
{% endblock content %}

accounts/templates/accounts/forgot_password.html
{% extends 'photo_template/base.html' %}

{% block title %}
SnapShare - Forgot Password
{% endblock title %}


{% block css %}

    body {
      background-color: #f8f9fa;
      cursor: url('https://i.imgur.com/DmBTFWT.png'), auto;
      color: #333;
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }

    .forgot-password {
      flex-grow: 1;
      display: flex;
      align-items: center;
      justify-content: center;
      text-align: center;
      background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://source.unsplash.com/random/1920x1080?photography');
      background-size: cover;
      background-position: center;
      color: #fff;
    }

    .forgot-password-form {
      max-width: 400px;
      background-color: rgba(255, 255, 255, 0.9);
      padding: 2rem;
      border-radius: 10px;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.3);
    }

    .forgot-password-form h2 {
      font-size: 2rem;
      font-weight: bold;
      margin-bottom: 1.5rem;
      text-align: center;
    }

    .forgot-password-form .form-group {
      margin-bottom: 1.5rem;
    }

    .forgot-password-form .form-control {
      border-radius: 0;
      background-color: transparent;
      border: none;
      border-bottom: 2px solid #ff4d4d;
      color: #333;
      font-size: 1rem;
      padding: 0.5rem 0;
    }

    .forgot-password-form .form-control:focus {
      background-color: transparent;
      border-color: #e63333;
      box-shadow: none;
    }

    .forgot-password-form .btn {
      background-color: #ff4d4d;
      color: #fff;
      font-weight: bold;
      border-radius: 0;
      transition: background-color 0.3s ease-in-out;
    }

    .forgot-password-form .btn:hover {
      background-color: #e63333;
    }

{% endblock css %}


{% block content %}
  <main class="forgot-password">
    <div class="container">
      <div class="forgot-password-form animate__animated animate__fadeInUp">
        <h2 class="text-dark">Forgot Password</h2>
        <form action="{% url 'accounts:forgot_password' %}" method="POST">
            {% csrf_token %}
          <div class="form-group">
            <input name="email" type="email" class="form-control" placeholder="Type In Your Email">
          </div>
          <button type="submit" class="btn btn-block">Send Reset Password Link</button>
        </form>
      </div>
    </div>
  </main>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'photo_template/base.html' %}

{% load static %}
{% block title %}
  SnapShare - Login
{% endblock title %}



{% block css %}
  
    body {
      background-color: #f8f9fa;
      cursor: url('https://i.imgur.com/DmBTFWT.png'), auto;
      color: #333;
      display: flex;
      flex-direction: column;
      background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://source.unsplash.com/random/1920x1080?photography');
      background-size: cover;
      background-position: center;
      min-height: 100vh;
    }

    .login {
      flex-grow: 1;
      display: flex;
      align-items: center;
      justify-content: center;
      text-align: center;
      
      color: #fff;
    }

    .login-form {
      max-width: 400px;
      background-color: rgba(255, 255, 255, 0.9);
      padding: 2rem;
      border-radius: 10px;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.3);
    }

    .login-form h2 {
      font-size: 2rem;
      font-weight: bold;
      margin-bottom: 1.5rem;
      text-align: center;
    }

    .login-form .form-group {
      margin-bottom: 1.5rem;
    }

    .login-form .form-control {
      border-radius: 0;
      background-color: transparent;
      border: none;
      border-bottom: 2px solid #ff4d4d;
      color: #333;
      font-size: 1rem;
      padding: 0.5rem 0;
    }

    .login-form .form-control:focus {
      background-color: transparent;
      border-color: #e63333;
      box-shadow: none;
    }

    .login-form .btn {
      background-color: #ff4d4d;
      color: #fff;
      font-weight: bold;
      border-radius: 0;
      transition: background-color 0.3s ease-in-out;
    }

    .login-form .btn:hover {
      background-color: #e63333;
    }

    .register-link {
      margin-top: 1rem;
      font-size: 0.9rem;
    }

    
  {% endblock css %}


  {% block content %}
      <!-- Main content -->
      {% if request.GET.command == 'verification' %}
      <div class="container mx-auto mb-5 alert alert-info text-center" role="alert" style="max-width: 600px; margin-top:100px; margin-bottom: 200%;">
          Thank you for registering with us. We have sent a verification link to <a style="text-decoration: underline;" class="text-success" href="https://mail.google.com/mail/u/0/">[{{request.GET.email}}]</a>.
  
          <br><br>
  
          Already verified? <a href="{% url 'accounts:login' %}">Login</a>
      </div>
  
      {% else %}
      <main class="login">
        <div class="container">
          <div class="login-form animate__animated animate__fadeInUp py-5">
            {% include 'photo_template/includes/alerts.html' %}
            <h2 class="text-dark">Login</h2>
            <form action="{% url 'accounts:login' %}" method="POST">
                {% csrf_token %}
              <div class="form-group">
                <input name="email" type="email" class="form-control" placeholder="Email">
              </div>
              <div class="form-group">
                <input name="password" type="password" class="form-control" placeholder="Password">
              </div>
              <button type="submit" class="btn btn-block">Login</button>
            </form>
            <div class="register-link text-dark">
              Forgot your password? <a href="{% url 'accounts:forgot_password' %}">Reset password</a>
            </div>
          </div>
        </div>
      </main>
    {% endif %}
{% endblock content %}

accounts/templates/accounts/reset_password.html
{% extends 'photo_template/base.html' %}

{% load static %}
{% block title %}
  SnapShare - Login
{% endblock title %}



{% block css %}
  
    body {
      background-color: #f8f9fa;
      cursor: url('https://i.imgur.com/DmBTFWT.png'), auto;
      color: #333;
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }

    .login {
      flex-grow: 1;
      display: flex;
      align-items: center;
      justify-content: center;
      text-align: center;
      background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://source.unsplash.com/random/1920x1080?photography');
      background-size: cover;
      background-position: center;
      color: #fff;
    }

    .login-form {
      max-width: 400px;
      background-color: rgba(255, 255, 255, 0.9);
      padding: 2rem;
      border-radius: 10px;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.3);
    }

    .login-form h2 {
      font-size: 2rem;
      font-weight: bold;
      margin-bottom: 1.5rem;
      text-align: center;
    }

    .login-form .form-group {
      margin-bottom: 1.5rem;
    }

    .login-form .form-control {
      border-radius: 0;
      background-color: transparent;
      border: none;
      border-bottom: 2px solid #ff4d4d;
      color: #333;
      font-size: 1rem;
      padding: 0.5rem 0;
    }

    .login-form .form-control:focus {
      background-color: transparent;
      border-color: #e63333;
      box-shadow: none;
    }

    .login-form .btn {
      background-color: #ff4d4d;
      color: #fff;
      font-weight: bold;
      border-radius: 0;
      transition: background-color 0.3s ease-in-out;
    }

    .login-form .btn:hover {
      background-color: #e63333;
    }

    .register-link {
      margin-top: 1rem;
      font-size: 0.9rem;
    }

    
  {% endblock css %}


  {% block content %}
  <main class="login">
    <div class="container">
      <div class="login-form animate__animated animate__fadeInUp py-5">
        {% include 'photo_template/includes/alerts.html' %}
        <h2 class="text-dark">Login</h2>
        <form action="{% url 'accounts:reset_password' %}" method="POST">
            {% csrf_token %}
          <div class="form-group">
            <input name="password" type="password" class="form-control" placeholder="Type In New Password">
          </div>
          <div class="form-group">
            <input name="confirm_password" type="password" class="form-control" placeholder="Type In Password To Confirm">
          </div>
          <button type="submit" class="btn btn-block">Reset Password</button>
        </form>
      </div>
    </div>
  </main>
{% endblock content %}

accounts/templates/accounts/reset_password_link.html
{% autoescape off %}
Hi {{ user.first_name }},

Please click on the below link to reset your account.
http://{{ domain }}{% url 'accounts:reset_password_validate' uidb64=uid token=token account_type=user_type %}

If you think it is not you that requested for this link, please ignore.

{% endautoescape %}